### ISSUE TITLE
IndexedSet does not work correctly with negative indexes in slices

### ISSUE THREAD

**Issue by darlove** [mahmoud/boltons#274] opened 2021-01-01 11:35 UTC
Hi there.

I have an indexed set with thousands of ints in it but this `s[-4:-1]` returns an empty set, `IndexedSet([ ])`. Slicing with positive bounds seems to work fine, though. You can easily get rid of this bug if you use the `slice` object that has all the necessary machinery to turn negative indexes into the standard positive ones. Just explore `slice`.

Thanks.

Best regards,
Darek

**Comment by mahmoud** [comment] 2021-01-04 18:04
Ah, I remember struggling with this way back when IndexedSet was first taking shape. Can you help get the ball rolling with a reproducing case? Copy/paste of a REPL session right here in the thread works fine. Thanks!

**Comment by ypankovych** [comment] 2021-01-05 14:47
Yeah, get us some reprosteps. BC it seems to work fine for me:
```python
>>> from boltons.setutils import IndexedSet
>>> s = IndexedSet(range(10000))
>>> s[-4:-1]
IndexedSet([9996, 9997, 9998])
```

**Comment by mahmoud** [comment] 2021-05-17 00:59
Closing, as we can't reproduce.

**Closed by mahmoud** 2021-05-17 00:59 UTC
